export const ROLES = {
    SYSTEM_ADMINISTRATOR: "SYSTEM_ADMINISTRATOR",
    INTERNAL_AUDITOR: "INTERNAL_AUDITOR",
    AUDIT_MANAGER: "AUDIT_MANAGER",
    CHIEF_AUDIT_EXECUTIVE: "CHIEF_AUDIT_EXECUTIVE",
    RISK_OFFICER: "RISK_OFFICER",
    AUDITEE: "AUDITEE",
    COMPLIANCE_OFFICER: "COMPLIANCE_OFFICER",
  };