package com.example.audit_risk_management.service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import com.example.audit_risk_management.dto.ApiResponse;
import com.example.audit_risk_management.dto.ReportRequestDTO;
import com.example.audit_risk_management.dto.ReportResponseDTO;
import com.example.audit_risk_management.enums.ReportStatus;
import com.example.audit_risk_management.enums.ReportType;

public interface ReportService {


    // ================= CREATE REPORT =================

    ApiResponse<ReportResponseDTO> createReport(
            ReportRequestDTO request);



    // ================= GET ALL REPORTS =================

    ApiResponse<List<ReportResponseDTO>> getAllReports();



    // ================= GET BY ID =================

    ApiResponse<ReportResponseDTO> getReportById(
            Long id);



    // ================= GET BY REPORT ID =================

    ApiResponse<ReportResponseDTO> getReportByReportId(
            String reportId);



    // ================= UPDATE REPORT =================

    ApiResponse<ReportResponseDTO> updateReport(
            Long id,
            ReportRequestDTO request);



    // ================= DELETE REPORT =================

    ApiResponse<String> deleteReport(
            Long id);



    // ================= FILTER METHODS =================


    // Reports generated by user

    ApiResponse<List<ReportResponseDTO>> getReportsByUser(
            Long userId);



    // Reports by type

    ApiResponse<List<ReportResponseDTO>> getReportsByType(
            ReportType reportType);



    // Reports by status

    ApiResponse<List<ReportResponseDTO>> getReportsByStatus(
            ReportStatus status);



    // Risk related reports

    ApiResponse<List<ReportResponseDTO>> getReportsByRisk(
            Long riskId);



    // KRI related reports

    ApiResponse<List<ReportResponseDTO>> getReportsByKri(
            Long kriId);



    // Mitigation related reports

    ApiResponse<List<ReportResponseDTO>> getReportsByMitigation(
            Long mitigationId);



    // Search

    ApiResponse<List<ReportResponseDTO>> searchReports(
            String keyword);



    // Date range

    ApiResponse<List<ReportResponseDTO>> getReportsBetweenDates(
            LocalDateTime startDate,
            LocalDateTime endDate);



    // Latest reports

    ApiResponse<List<ReportResponseDTO>> getLatestReports();



    // ================= DASHBOARD =================


    ApiResponse<Map<String, Long>> getReportDashboard();

}