package com.example.audit_risk_management.model;

import java.time.LocalDateTime;

import com.example.audit_risk_management.enums.ReportStatus;
import com.example.audit_risk_management.enums.ReportType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

@Entity
@Table(name = "reports")
public class Report {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Example: REP-001
    @Column(unique = true, nullable = false)
    private String reportId;


    @Column(nullable = false)
    private String reportTitle;


    @Column(length = 1000)
    private String description;


    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportType reportType;


    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportStatus status = ReportStatus.GENERATED;



    // Report generated by user
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "generated_by", nullable = false)
    private User generatedBy;



    // Optional relation with Risk
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "risk_id")
    private Risk risk;



    // Optional relation with KRI
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "kri_id")
    private Kri kri;



    // Optional relation with Mitigation
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mitigation_id")
    private Mitigation mitigation;



    private String fileName;

    private String filePath;



    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;


    private LocalDateTime updatedAt;



    @PrePersist
    public void onCreate(){

        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();

        if(status == null){
            status = ReportStatus.GENERATED;
        }
    }



    @PreUpdate
    public void onUpdate(){

        updatedAt = LocalDateTime.now();
    }



    public Report(){

    }



    // Getters & Setters


    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public String getReportId() {
        return reportId;
    }


    public void setReportId(String reportId) {
        this.reportId = reportId;
    }


    public String getReportTitle() {
        return reportTitle;
    }


    public void setReportTitle(String reportTitle) {
        this.reportTitle = reportTitle;
    }


    public String getDescription() {
        return description;
    }


    public void setDescription(String description) {
        this.description = description;
    }


    public ReportType getReportType() {
        return reportType;
    }


    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }


    public ReportStatus getStatus() {
        return status;
    }


    public void setStatus(ReportStatus status) {
        this.status = status;
    }


    public User getGeneratedBy() {
        return generatedBy;
    }


    public void setGeneratedBy(User generatedBy) {
        this.generatedBy = generatedBy;
    }


    public Risk getRisk() {
        return risk;
    }


    public void setRisk(Risk risk) {
        this.risk = risk;
    }


    public Kri getKri() {
        return kri;
    }


    public void setKri(Kri kri) {
        this.kri = kri;
    }


    public Mitigation getMitigation() {
        return mitigation;
    }


    public void setMitigation(Mitigation mitigation) {
        this.mitigation = mitigation;
    }


    public String getFileName() {
        return fileName;
    }


    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


    public String getFilePath() {
        return filePath;
    }


    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }


    public LocalDateTime getCreatedAt() {
        return createdAt;
    }


    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

}