package com.example.audit_risk_management.repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.example.audit_risk_management.enums.ReportStatus;
import com.example.audit_risk_management.enums.ReportType;
import com.example.audit_risk_management.model.Report;


@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {


    // Find report using custom report ID (REP-001)
    Optional<Report> findByReportId(String reportId);


    // Check duplicate report ID
    boolean existsByReportId(String reportId);



    // Reports generated by a particular user
    List<Report> findByGeneratedBy_Id(Long userId);



    // Reports by type
    // RISK_REPORT, KRI_REPORT, AUDIT_REPORT
    List<Report> findByReportType(ReportType reportType);



    // Reports by status
    // GENERATED, PENDING, FAILED
    List<Report> findByStatus(ReportStatus status);



    // Find reports related to a Risk
    List<Report> findByRisk_Id(Long riskId);



    // Find reports related to a KRI
    List<Report> findByKri_Id(Long kriId);



    // Find reports related to a Mitigation
    List<Report> findByMitigation_Id(Long mitigationId);



    // Search report by title
    List<Report> findByReportTitleContainingIgnoreCase(String keyword);



    // Reports between dates
    List<Report> findByCreatedAtBetween(
            LocalDateTime startDate,
            LocalDateTime endDate);



    // Latest generated reports
    List<Report> findTop10ByOrderByCreatedAtDesc();



    // Count reports by type for dashboard

    long countByReportType(ReportType reportType);



    // Count reports by status

    long countByStatus(ReportStatus status);



    // Delete report by report ID

    void deleteByReportId(String reportId);

}